import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";
import ShoppingProvider from "./UtlitesAndProviders/ShoppingProvider";
import ShoppingCartModel from "@/components/ShoppingCartModel/ShoppingCartModel";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShoppingProvider>
          <NavBar />
          <ShoppingCartModel />
          {children}
        </ShoppingProvider>
      </body>
    </html>
  );
}
